---
title: "A taste of text mining"
author: 'Nicholas Horton (nhorton@amherst.edu)'
date: 'November 5, 2015'
output:
  pdf_document:
    fig_height: 6
    fig_width: 6
  html_document:
    fig_height: 3
    fig_width: 5
  word_document:
    fig_height: 3
    fig_width: 5
---


```{r include=FALSE}
# Don't delete this chunk if you are using the mosaic package
# This loads the mosaic and dplyr packages
require(mosaic)
```

```{r include=FALSE}
# Some customization.  You can alter or delete as desired (if you know what you are doing).

# This changes the default colors in lattice plots.
trellis.par.set(theme=theme.mosaic())  

# knitr settings to control how R chunks work.
require(knitr)
opts_chunk$set(
  tidy=FALSE,     # display code as typed
  size="small"    # slightly smaller font for code
)
# This loads the mosaic data sets.  (Could be deleted if you are not using them.)
require(mosaicData)   
```


```{r message=FALSE}
require(tm)
require(aRxiv)
require(lubridate)
require(stringr)
require(wordcloud)
# papers <- arxiv_search(query='au:"Tibshirani" AND cat:stat*', limit=50)
download.file("http://www.amherst.edu/~nhorton/stat495/Tibshirani.Rda", "Tibshirani.Rda")
load("Tibshirani.Rda")
```

```{r}
names(papers)
dim(papers)
papers <- mutate(papers, submityear =
  year(sapply(str_split(submitted, " "), "[[", 1)))
with(papers, table(submityear))
```

```{r}
location <- "abstracts"
if (!file.exists(location)) {
 dir.create(location)
}
for (i in 1:nrow(papers)) {
 cat(papers$abstract[i], file=paste(location, "/papers", i, sep=""))
}
```

```{r}
mycorpus <- VCorpus(DirSource(location))
inspect(mycorpus[1])
mycorpus <- tm_map(mycorpus, stripWhitespace)
mycorpus <- tm_map(mycorpus, removeNumbers)
mycorpus <- tm_map(mycorpus, removePunctuation)
mycorpus <- tm_map(mycorpus, content_transformer(tolower))
mycorpus <- tm_map(mycorpus, removeWords, stopwords("english"))
inspect(mycorpus[1])
```

```{r}
dtm = DocumentTermMatrix(mycorpus)
```

```{r}
findFreqTerms(dtm, 7)
findAssocs(dtm, "bootstrap", 0.7)
inspect(dtm[1:3, 1:3])

```

```{r eval=FALSE}
wordcount <- apply(inspect(dtm[,]), 2, sum)
sorted <- sort(wordcount, decreasing=TRUE)
head(sorted)
```

```{r warning=FALSE}
wordcloud(mycorpus, max.words = 35)
```